[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.2"

[[constraint]]
  branch = "master"
  name = "github.com/whyrusleeping/cbor"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
